apiVersion: v1
kind: Service
metadata:
  name: q7-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30100
  selector:
    app: q7-FinalExam